@extends('layouts.app')
@section('content')
<div class="font-sans text-slate-900 bg-white overflow-x-hidden">
    @include('home.hero')
    @include('home.categories')
    @include('home.portals')
    @include('home.featured-products')
    @include('home.why')
    @include('home.stats')
    @include('home.partners')
    @include('home.services')
    @include('home.tracking-showcase')
    @include('home.process')
    @include('home.testimonials')
    @include('home.cta')
    @include('home.compliance')
    @include('home.coverage')
</div>
@endsection
